### ISSUE TITLE
Add support for running in AOT

### ISSUE THREAD

**Issue by nloum** [extism/dotnet-sdk#63]
Currently when I depend on the Extism SDK from my C# AOT command line program, I get this error:

```
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Extism.Sdk.Plugin..ctor(Manifest manifest, HostFunction[] functions, Boolean withWasi)
```

This is because Extism is trying to serialize the manifest as JSON using reflection on this line right here:

https://github.com/extism/dotnet-sdk/blob/234610e4e7f45f4c7c43fcbf3b7443b2821a553a/src/Extism.Sdk/Plugin.cs#L49

There's a lot more information here: https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/

To reproduce this error, depend on the Extism SDK and add these lines to your csproj:

```
    <PropertyGroup>
        <PublishAot>true</PublishAot>
    </PropertyGroup>
```

Can we add support for running this library from .NET AOT? I don't mind contributing.

**Comment by mhmd-azeez** [comment]
Hi @nloum, great catch!

> Can we add support for running this library from .NET AOT? I don't mind contributing.

Absolutely, please do! Let me know if you need anything to get started, I'd be happy to help

**Comment by mhmd-azeez** [comment]
We also have a dotnet-sdk channel in our discord server:
https://discord.gg/myuWqjBq

Feel free to ask questions either here, or on Discord
